application: supernoobabhi
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:
- url: /js
  static_dir: js
- url: /txt
  static_dir: txt

- url: /txt
  static_dir: txt

- url: /.*
  script: main.application
    
